name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  learn-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create test file
        uses: touch test.txt

      - name: Say Hello and save it to test file
        run: echo "Hi there! I'm the CI Github Action!" > test.txt

      - name: Show date
        run: date

